### ISSUE TITLE
Android Studio support 

### ISSUE THREAD

**Issue by jpoep** [google/watchface#28]
Hi,

sorry if this is the wrong place to ask but documentation around this topic seems pretty scarce and I wasn't able to find anything that answers my questions.

Is this project integrated to Android Studio in any way? It looks like it doesn't verify my XML files using the XSDs provided in this repository and also doesn't provide any graphical editing support. 

While validating my XML using other software, like VSCode's XML extension by RedHat, does kind of work, it raises a lot of errors that seem to be present in the schema itself (tested with 2/watchface.xsd). Surely this can't be the intended development workflow? If not, what is? 

I also tried using Watch Face Studio but it doesn't seem to be supporting V2 whatsoever. Am I missing something?

Thanks a ton for your help!

**Comment by garanj** [comment]
Hi @jpoep - the XML validation with an editor poses a problem today: The watch face XSD uses schema version 1.1 whereas (to my knowledge) VSCode can only work with 1.0, so you'll see errors from VSCode when it tries to interpret the watch face XSD.

There are editors available that do support 1.1, though I think many of them are commercial offerings and I can't recommend one over another.

We'll continue to look for solutions to this.
